# Generated by Django 2.0.3 on 2018-03-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
