# Generated by Django 2.0.3 on 2018-04-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0005_auto_20180414_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
