# Generated by Django 2.0.3 on 2018-11-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_messages', '0006_auto_20180415_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
